Add types to LayoutManager to avoid:
ERROR in ./src/app/builder/components/layout/LayoutManager.tsx
(107,28): error TS2339: Property 'x' does not exist on type '{}'.